// flow-typed signature: 5a01213e5c477532b9ce19ab95c77795
// flow-typed version: <<STUB>>/ejs_v3.1.5/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ejs/bin/cli' {
  declare module.exports: any;
}

declare module 'ejs/ejs' {
  declare module.exports: any;
}

declare module 'ejs/ejs.min' {
  declare module.exports: any;
}

declare module 'ejs/jakefile' {
  declare module.exports: any;
}

declare module 'ejs/lib/ejs' {
  declare module.exports: any;
}

declare module 'ejs/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ejs/bin/cli.js' {
  declare module.exports: $Exports<'ejs/bin/cli'>;
}
declare module 'ejs/ejs.js' {
  declare module.exports: $Exports<'ejs/ejs'>;
}
declare module 'ejs/ejs.min.js' {
  declare module.exports: $Exports<'ejs/ejs.min'>;
}
declare module 'ejs/jakefile.js' {
  declare module.exports: $Exports<'ejs/jakefile'>;
}
declare module 'ejs/lib/ejs.js' {
  declare module.exports: $Exports<'ejs/lib/ejs'>;
}
declare module 'ejs/lib/utils.js' {
  declare module.exports: $Exports<'ejs/lib/utils'>;
}
